### ISSUE TITLE
Chat client disconnects when app is left idle for long period of time

### ISSUE THREAD

**Issue by uddinr** [twilio/ip-demo-ios#58] opened 2020-12-02 20:28 UTC
Hi,

We are implementing the Twilio iOS Chat SDK, when the app is sent to the background or left in the foreground idle for a long time, it seems subsequent calls to the sdk seem to timeout.

Is there something we need to do to ensure the client doesnt timeout over long periods of execution? From the twilio documentation here:

https://www.twilio.com/docs/chat/best-practices-sdk-clients

Under sdk lifecycles, do we need to shutdown the client when app goes in background and reinitialise when in the foreground?

**Comment by uddinr** [comment] 2020-12-03 10:26
it seems when the app returns to foreground the client status is disconnected and does not attempt to reconnect

also if you manually shutdown on the client and check its status it is still reported as connected and the synchronizationStatusUpdated method is not being called

**Comment by berkus** [comment] 2020-12-03 10:29
The ios chat sdk listens for the applicationWasBackgrounded: and Foregrounded: events and triggers reconnection after it was foregrounded.

Please collect and provide Trace level logs from the SDK if it doesn't for you - we will investigate.

**Comment by uddinr** [comment] 2020-12-03 10:32
any reason why the connection status on the client would still be connected even though the client has been shutdown?

**Comment by berkus** [comment] 2020-12-03 10:39
After `[client shutdown]`, calls to`[client connectionState]` should return `TCHClientConnectionStateUnknown`.

**Comment by uddinr** [comment] 2020-12-03 10:43
<img width="407" alt="Screenshot 2020-12-03 at 10 42 28" src="https://user-images.githubusercontent.com/18418023/100999161-4c62cb00-3554-11eb-8528-f0abed522c40.png">

after calling shutdown() the client is still connected and the synchronizationStatusUpdated method is never called

**Comment by berkus** [comment] 2020-12-03 11:01
Ok, we'll try to reproduce this.

**Comment by berkus** [comment] 2020-12-14 22:19
What is your Twilio Chat SDK version btw?

**Comment by uddinr** [comment] 2020-12-15 11:09
we are using version 4.0.1

**Comment by berkus** [comment] 2020-12-16 08:14
Ok, thanks for the info!

**Comment by Yulia8294** [comment] 2021-02-11 09:59
Hi! We're having the same issue. Sometimes when the app returns to foreground - it would not reconnect, resulting in all requests fail with timeout. It also won't reconnect when internet connection goes off for a minute or more, although it's stated in the docs that it should reconnect on its own. In both cases neither synchronizationStatusUpdated nor connectionStateUpdated is called. Could you suggest what might be the issue or otherwise a recommended way of manual reconnection in these 2 cases. Thanks!

[Logs.txt](https://github.com/twilio/twilio-chat-demo-ios/files/5964334/Logs.txt)

**Comment by borut-t** [comment] 2021-03-10 13:27
I'm also facing a similar issue when the app is left in the background or idle for a certain period, getting back to the app I can see the console logs "Socket is not connected". And any command sent to the client timeouts. Cannot really reproduce this issue, but it is happening, and don't really know what to do here.

SDK version is `4.1.0`.

**Comment by berkus** [comment] 2021-03-10 13:33
@Yulia8294 @borut-t we've identified some related issues and are testing a possible fix right now. Stay tuned!

**Comment by borut-t** [comment] 2021-03-12 08:37
When I am within a channel and I put the app into the background, then resume it and try to send the message, a timeout occurs.
The internet connection on the iPhone works since I've tried it out just before resuming the app.
As you can see from the logs, SDK is unable to reconnect.

Also, it looks like that I cannot interact anymore on this channel at this stage. If I go to another channel, I can send messages and interact normally. But this channel I've resumed too, I cannot do anything until I restart the app.

Very very interesting. I think you should look at it.

Please check the attached log...

[Twilio-app-resume.txt](https://github.com/twilio/twilio-chat-demo-ios/files/6128623/Twilio-app-resume.txt)

**Comment by Gray-Wind** [comment] 2021-03-24 14:14
We've released Chat Client with version 4.2.0. This issue should be fixed.

**Comment by Gray-Wind** [comment] 2021-03-24 14:15
Feel free to comment here if you have any questions or to create a new ticket.

**Comment by borut-t** [comment] 2021-04-02 11:57
@Gray-Wind I don't think this issue is fixed. I'm using Conversations SDK now but it still timeouts from time to time. 
This is especially evident after the app is in the background for a while and after tapping push notification to open the app, the channel on which I redirect the user cannot retrieve messages. It just loads until I get a timeout.

**Comment by Yulia8294** [comment] 2021-04-02 17:44
@Gray-Wind Hi, also tried the new version and issue was reproducing from time to time.

**Comment by Gray-Wind** [comment] 2021-04-03 18:14
Thank you, we will make a fix asap.

**Comment by borut-t** [comment] 2021-04-12 15:58
@Gray-Wind where are we with this? This issue is really annoying and a deal-breaker. We are already doing some hacks around this but I would like to have a proper solution.

When can we expect a fix for that issue?

**Comment by Gray-Wind** [comment] 2021-04-12 16:01
We are working on a solution with all available sources. I cannot give any ETA at the moment, but this issue is our number one priority right now.

**Comment by Gray-Wind** [comment] 2021-05-05 06:19
iOS Chat SDK 4.2.1 with fixes around connectivity has been released!

**Closed as completed by Gray-Wind** 2021-05-05 06:19 UTC
