### ISSUE TITLE
Any ideas on how to get rid of the following error messages? Also, looks like messages are not sending.

### ISSUE THREAD

**Issue by cwhite333** [twilio/ip-demo-ios#38] opened 2018-03-12 18:10 UTC
2018-03-12 09:57:04.844783-0700 ChatQuickstart[36885:11842858] [MC] Lazy loading NSBundle MobileCoreServices.framework
2018-03-12 09:57:04.846703-0700 ChatQuickstart[36885:11842858] [MC] Loaded MobileCoreServices.framework
2018-03-12 09:57:07.517080-0700 ChatQuickstart[36885:11843149] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> TNTwilsockClient[2]:     0x700001889000 | 03/12/09:57:07.515 | WARNING  | 1      | TNTwilsockClient | Reply status for init request is not success: 401, AUTHENTICATION_FAILED
2018-03-12 09:57:07.612691-0700 ChatQuickstart[36885:11843149] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> TNTransportDisconnectingState[2]:     0x700001889000 | 03/12/09:57:07.612 | WARNING  | 11     | TNTransportDisconnectingState | Success reply can not be sent. Twilsock is not in connected state
2018-03-12 09:57:07.613604-0700 ChatQuickstart[36885:11843149] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> TNTransportDisconnectingState[2]:     0x700001889000 | 03/12/09:57:07.612 | WARNING  | 11     | TNTransportDisconnectingState | Disconnect procedure has been already started
2018-03-12 09:57:12.056329-0700 ChatQuickstart[36885:11843151] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> TCHttpObserver[2]:     0x70000198f000 | 03/12/09:57:12.056 | WARNING  | 9      | TCHttpObserver | Request has failed: Transport connection closed (3)
2018-03-12 09:57:17.061394-0700 ChatQuickstart[36885:11843155] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> TCHttpObserver[2]:     0x700001b9b000 | 03/12/09:57:17.060 | WARNING  | 12     | TCHttpObserver | Request has failed: Transport connection closed (3)
2018-03-12 09:57:22.066065-0700 ChatQuickstart[36885:11843159] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> TCHttpObserver[2]:     0x700001da7000 | 03/12/09:57:22.065 | WARNING  | 13     | TCHttpObserver | Request has failed: Transport connection closed (3)
2018-03-12 09:57:22.090392-0700 ChatQuickstart[36885:11843124] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> Chat-iOS[0]:     0x7000015fa000 | 03/12/09:57:22.089 | FATAL    | Chat-iOS | Error validating token: 3
2018-03-12 09:57:43.617410-0700 ChatQuickstart[36885:11844297] [BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
2018-03-12 09:57:43.617881-0700 ChatQuickstart[36885:11844297] [BoringSSL] Function boringssl_session_errorlog: line 2871 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
2018-03-12 09:57:43.618088-0700 ChatQuickstart[36885:11844297] TIC Read Status [1:0x604000176080]: 1:57
2018-03-12 09:57:43.618347-0700 ChatQuickstart[36885:11844297] TIC Read Status [1:0x604000176080]: 1:57
2018-03-12 09:57:43.618530-0700 ChatQuickstart[36885:11844297] TIC Read Status [1:0x604000176080]: 1:57
2018-03-12 09:58:22.059580-0700 ChatQuickstart[36885:11842858] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/christianwhite/Library/Developer/CoreSimulator/Devices/3E4B7D98-CB4C-4FDA-A93E-7EAC63182BBC/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-03-12 09:58:22.061782-0700 ChatQuickstart[36885:11842858] [MC] Reading from private effective user settings.
2018-03-12 09:58:23.396826-0700 ChatQuickstart[36885:11842858] libMobileGestalt MobileGestalt.c:1402: Could not retrieve region info

**Comment by rbeiter** [comment] 2018-03-13 07:52
It looks like this is likely to be the key message in this log:

`2018-03-12 09:57:07.517080-0700 ChatQuickstart[36885:11843149] <<<<TwilioChatClient: 0x7fc80ac1bad0>>>> TNTwilsockClient[2]: 0x700001889000 | 03/12/09:57:07.515 | WARNING | 1 | TNTwilsockClient | Reply status for init request is not success: 401, AUTHENTICATION_FAILED`

This generally means your access token is not valid.  Can you please open a ticket at https://support.twilio.com/hc/en-us/requests/new referencing this github issue so it gets routed to me?  Please include an example access token (not here on github though for privacy reasons) and we'll work with you to resolve this.

Thank you,
Randy

**Comment by rbeiter** [comment] 2018-08-21 18:12
Hi @cwhite333, closing this older issue as it seems the root cause was an invalid token.  Please re-open if you are still having experiencing issues.

**Closed as completed by rbeiter** 2018-08-21 18:12 UTC
